### ISSUE TITLE
Notes on HTML

### ISSUE THREAD

**Issue by SidTheEngineer** [pokumars/tea-cozy#1]
Overall, the formatting and organization of your HTML look great! All of the different types of elements look to be used appropriately and in the right places. 

One small area for improvement has to do with the links in the navigation bar. Right now, when we click these links they have no functionality. We can tie these links to sections of the site so that when clicked, they take the user to the respective section. This is done by taking advantage of the `href` attribute on the `<a>` tag. Instead of simply doing `href="#"` we can link to the id of a specific element in our HTML by doing `href="#nameOfId"`.

**Comment by pokumars** [comment]
link-destinations fixed.
